
namespace BigAds.FormDetail
{
    partial class FormBsy
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormBsy));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties53 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties54 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties55 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties56 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties49 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties50 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties51 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties52 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.label3 = new System.Windows.Forms.Label();
            this.button2 = new System.Windows.Forms.Button();
            this.button1 = new System.Windows.Forms.Button();
            this.btnOk = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnExit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.txttenBsy = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtmBsy = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.txtChuyenKhoa = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label5 = new System.Windows.Forms.Label();
            this.txtExp = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label6 = new System.Windows.Forms.Label();
            this.txtbcap = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label7 = new System.Windows.Forms.Label();
            this.txtPhone = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label8 = new System.Windows.Forms.Label();
            this.txtDcBsy = new Bunifu.UI.WinForms.BunifuTextBox();
            this.SuspendLayout();
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(12, 8);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(55, 16);
            this.label3.TabIndex = 31;
            this.label3.Text = "Bác sỹ";
            // 
            // button2
            // 
            this.button2.AutoEllipsis = true;
            this.button2.FlatAppearance.BorderSize = 0;
            this.button2.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.button2.Image = global::BigAds.Properties.Resources.Icon_16x16;
            this.button2.Location = new System.Drawing.Point(719, 5);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(30, 23);
            this.button2.TabIndex = 39;
            this.button2.UseVisualStyleBackColor = false;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            // 
            // button1
            // 
            this.button1.AutoEllipsis = true;
            this.button1.FlatAppearance.BorderSize = 0;
            this.button1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.button1.Image = global::BigAds.Properties.Resources._43__2_;
            this.button1.Location = new System.Drawing.Point(755, 5);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(31, 23);
            this.button1.TabIndex = 38;
            this.button1.UseVisualStyleBackColor = false;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // btnOk
            // 
            this.btnOk.AllowAnimations = true;
            this.btnOk.AllowMouseEffects = true;
            this.btnOk.AllowToggling = false;
            this.btnOk.AnimationSpeed = 200;
            this.btnOk.AutoGenerateColors = false;
            this.btnOk.AutoRoundBorders = false;
            this.btnOk.AutoSizeLeftIcon = true;
            this.btnOk.AutoSizeRightIcon = true;
            this.btnOk.BackColor = System.Drawing.Color.Transparent;
            this.btnOk.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(123)))), ((int)(((byte)(255)))));
            this.btnOk.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnOk.BackgroundImage")));
            this.btnOk.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOk.ButtonText = "     Lưu";
            this.btnOk.ButtonTextMarginLeft = 0;
            this.btnOk.ColorContrastOnClick = 45;
            this.btnOk.ColorContrastOnHover = 45;
            this.btnOk.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnOk.CustomizableEdges = borderEdges3;
            this.btnOk.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnOk.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOk.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOk.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOk.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnOk.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold);
            this.btnOk.ForeColor = System.Drawing.Color.Transparent;
            this.btnOk.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOk.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnOk.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnOk.IconMarginLeft = 11;
            this.btnOk.IconPadding = 10;
            this.btnOk.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOk.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnOk.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnOk.IconSize = 25;
            this.btnOk.IdleBorderColor = System.Drawing.Color.Blue;
            this.btnOk.IdleBorderRadius = 10;
            this.btnOk.IdleBorderThickness = 1;
            this.btnOk.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(123)))), ((int)(((byte)(255)))));
            this.btnOk.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnOk.IdleIconLeftImage")));
            this.btnOk.IdleIconRightImage = null;
            this.btnOk.IndicateFocus = false;
            this.btnOk.Location = new System.Drawing.Point(290, 211);
            this.btnOk.Name = "btnOk";
            this.btnOk.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOk.OnDisabledState.BorderRadius = 10;
            this.btnOk.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOk.OnDisabledState.BorderThickness = 1;
            this.btnOk.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOk.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOk.OnDisabledState.IconLeftImage = null;
            this.btnOk.OnDisabledState.IconRightImage = null;
            this.btnOk.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnOk.onHoverState.BorderRadius = 10;
            this.btnOk.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOk.onHoverState.BorderThickness = 1;
            this.btnOk.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(105)))), ((int)(((byte)(217)))));
            this.btnOk.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnOk.onHoverState.IconLeftImage = null;
            this.btnOk.onHoverState.IconRightImage = null;
            this.btnOk.OnIdleState.BorderColor = System.Drawing.Color.Blue;
            this.btnOk.OnIdleState.BorderRadius = 10;
            this.btnOk.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOk.OnIdleState.BorderThickness = 1;
            this.btnOk.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(123)))), ((int)(((byte)(255)))));
            this.btnOk.OnIdleState.ForeColor = System.Drawing.Color.Transparent;
            this.btnOk.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnOk.OnIdleState.IconLeftImage")));
            this.btnOk.OnIdleState.IconRightImage = null;
            this.btnOk.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnOk.OnPressedState.BorderRadius = 10;
            this.btnOk.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOk.OnPressedState.BorderThickness = 1;
            this.btnOk.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnOk.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnOk.OnPressedState.IconLeftImage = null;
            this.btnOk.OnPressedState.IconRightImage = null;
            this.btnOk.Size = new System.Drawing.Size(88, 39);
            this.btnOk.TabIndex = 36;
            this.btnOk.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnOk.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnOk.TextMarginLeft = 0;
            this.btnOk.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnOk.UseDefaultRadiusAndThickness = true;
            this.btnOk.Click += new System.EventHandler(this.btnOk_Click);
            // 
            // btnExit
            // 
            this.btnExit.AllowAnimations = true;
            this.btnExit.AllowMouseEffects = true;
            this.btnExit.AllowToggling = false;
            this.btnExit.AnimationSpeed = 200;
            this.btnExit.AutoGenerateColors = false;
            this.btnExit.AutoRoundBorders = false;
            this.btnExit.AutoSizeLeftIcon = true;
            this.btnExit.AutoSizeRightIcon = true;
            this.btnExit.BackColor = System.Drawing.Color.Transparent;
            this.btnExit.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(53)))), ((int)(((byte)(69)))));
            this.btnExit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnExit.BackgroundImage")));
            this.btnExit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExit.ButtonText = "    Hủy";
            this.btnExit.ButtonTextMarginLeft = 0;
            this.btnExit.ColorContrastOnClick = 45;
            this.btnExit.ColorContrastOnHover = 45;
            this.btnExit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnExit.CustomizableEdges = borderEdges4;
            this.btnExit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnExit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnExit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnExit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnExit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnExit.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold);
            this.btnExit.ForeColor = System.Drawing.Color.Transparent;
            this.btnExit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnExit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnExit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnExit.IconMarginLeft = 11;
            this.btnExit.IconPadding = 10;
            this.btnExit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnExit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnExit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnExit.IconSize = 25;
            this.btnExit.IdleBorderColor = System.Drawing.Color.Red;
            this.btnExit.IdleBorderRadius = 10;
            this.btnExit.IdleBorderThickness = 1;
            this.btnExit.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(53)))), ((int)(((byte)(69)))));
            this.btnExit.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnExit.IdleIconLeftImage")));
            this.btnExit.IdleIconRightImage = null;
            this.btnExit.IndicateFocus = false;
            this.btnExit.Location = new System.Drawing.Point(395, 212);
            this.btnExit.Name = "btnExit";
            this.btnExit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnExit.OnDisabledState.BorderRadius = 10;
            this.btnExit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExit.OnDisabledState.BorderThickness = 1;
            this.btnExit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnExit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnExit.OnDisabledState.IconLeftImage = null;
            this.btnExit.OnDisabledState.IconRightImage = null;
            this.btnExit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnExit.onHoverState.BorderRadius = 10;
            this.btnExit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExit.onHoverState.BorderThickness = 1;
            this.btnExit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(35)))), ((int)(((byte)(51)))));
            this.btnExit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnExit.onHoverState.IconLeftImage = null;
            this.btnExit.onHoverState.IconRightImage = null;
            this.btnExit.OnIdleState.BorderColor = System.Drawing.Color.Red;
            this.btnExit.OnIdleState.BorderRadius = 10;
            this.btnExit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExit.OnIdleState.BorderThickness = 1;
            this.btnExit.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(53)))), ((int)(((byte)(69)))));
            this.btnExit.OnIdleState.ForeColor = System.Drawing.Color.Transparent;
            this.btnExit.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnExit.OnIdleState.IconLeftImage")));
            this.btnExit.OnIdleState.IconRightImage = null;
            this.btnExit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnExit.OnPressedState.BorderRadius = 10;
            this.btnExit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExit.OnPressedState.BorderThickness = 1;
            this.btnExit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(53)))), ((int)(((byte)(69)))));
            this.btnExit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnExit.OnPressedState.IconLeftImage = null;
            this.btnExit.OnPressedState.IconRightImage = null;
            this.btnExit.Size = new System.Drawing.Size(87, 39);
            this.btnExit.TabIndex = 35;
            this.btnExit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnExit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnExit.TextMarginLeft = 0;
            this.btnExit.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnExit.UseDefaultRadiusAndThickness = true;
            this.btnExit.Click += new System.EventHandler(this.btnExit_Click);
            // 
            // bunifuFormDock1
            // 
            this.bunifuFormDock1.AllowFormDragging = true;
            this.bunifuFormDock1.AllowFormDropShadow = true;
            this.bunifuFormDock1.AllowFormResizing = true;
            this.bunifuFormDock1.AllowHidingBottomRegion = true;
            this.bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock1.ContainerControl = this;
            this.bunifuFormDock1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock1.DockingOptions.DockAll = true;
            this.bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock1.DockingOptions.DockLeft = true;
            this.bunifuFormDock1.DockingOptions.DockRight = true;
            this.bunifuFormDock1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock1.DockingOptions.DockTopRight = true;
            this.bunifuFormDock1.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock1.ParentForm = this;
            this.bunifuFormDock1.ShowCursorChanges = true;
            this.bunifuFormDock1.ShowDockingIndicators = true;
            this.bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock1;
            this.bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDock1.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(12, 44);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(59, 16);
            this.label1.TabIndex = 40;
            this.label1.Text = "Mã Bsỹ";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(362, 44);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(65, 16);
            this.label2.TabIndex = 42;
            this.label2.Text = "Tên Bsỹ";
            // 
            // txttenBsy
            // 
            this.txttenBsy.AcceptsReturn = false;
            this.txttenBsy.AcceptsTab = false;
            this.txttenBsy.AnimationSpeed = 200;
            this.txttenBsy.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txttenBsy.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txttenBsy.BackColor = System.Drawing.Color.Transparent;
            this.txttenBsy.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txttenBsy.BackgroundImage")));
            this.txttenBsy.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txttenBsy.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txttenBsy.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txttenBsy.BorderColorIdle = System.Drawing.Color.Silver;
            this.txttenBsy.BorderRadius = 10;
            this.txttenBsy.BorderThickness = 1;
            this.txttenBsy.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txttenBsy.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txttenBsy.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F);
            this.txttenBsy.DefaultText = "";
            this.txttenBsy.FillColor = System.Drawing.Color.White;
            this.txttenBsy.HideSelection = true;
            this.txttenBsy.IconLeft = null;
            this.txttenBsy.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txttenBsy.IconPadding = 10;
            this.txttenBsy.IconRight = null;
            this.txttenBsy.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txttenBsy.Lines = new string[0];
            this.txttenBsy.Location = new System.Drawing.Point(451, 35);
            this.txttenBsy.MaxLength = 32767;
            this.txttenBsy.MinimumSize = new System.Drawing.Size(1, 1);
            this.txttenBsy.Modified = false;
            this.txttenBsy.Multiline = false;
            this.txttenBsy.Name = "txttenBsy";
            stateProperties53.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties53.FillColor = System.Drawing.Color.Empty;
            stateProperties53.ForeColor = System.Drawing.Color.Empty;
            stateProperties53.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txttenBsy.OnActiveState = stateProperties53;
            stateProperties54.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties54.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties54.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties54.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txttenBsy.OnDisabledState = stateProperties54;
            stateProperties55.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties55.FillColor = System.Drawing.Color.Empty;
            stateProperties55.ForeColor = System.Drawing.Color.Empty;
            stateProperties55.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txttenBsy.OnHoverState = stateProperties55;
            stateProperties56.BorderColor = System.Drawing.Color.Silver;
            stateProperties56.FillColor = System.Drawing.Color.White;
            stateProperties56.ForeColor = System.Drawing.Color.Empty;
            stateProperties56.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txttenBsy.OnIdleState = stateProperties56;
            this.txttenBsy.Padding = new System.Windows.Forms.Padding(3);
            this.txttenBsy.PasswordChar = '\0';
            this.txttenBsy.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txttenBsy.PlaceholderText = "Enter text";
            this.txttenBsy.ReadOnly = false;
            this.txttenBsy.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txttenBsy.SelectedText = "";
            this.txttenBsy.SelectionLength = 0;
            this.txttenBsy.SelectionStart = 0;
            this.txttenBsy.ShortcutsEnabled = true;
            this.txttenBsy.Size = new System.Drawing.Size(332, 35);
            this.txttenBsy.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txttenBsy.TabIndex = 41;
            this.txttenBsy.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txttenBsy.TextMarginBottom = 0;
            this.txttenBsy.TextMarginLeft = 3;
            this.txttenBsy.TextMarginTop = 0;
            this.txttenBsy.TextPlaceholder = "Enter text";
            this.txttenBsy.UseSystemPasswordChar = false;
            this.txttenBsy.WordWrap = true;
            // 
            // txtmBsy
            // 
            this.txtmBsy.AcceptsReturn = false;
            this.txtmBsy.AcceptsTab = false;
            this.txtmBsy.AnimationSpeed = 200;
            this.txtmBsy.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtmBsy.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtmBsy.BackColor = System.Drawing.Color.Transparent;
            this.txtmBsy.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtmBsy.BackgroundImage")));
            this.txtmBsy.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtmBsy.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtmBsy.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtmBsy.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtmBsy.BorderRadius = 10;
            this.txtmBsy.BorderThickness = 1;
            this.txtmBsy.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtmBsy.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtmBsy.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F);
            this.txtmBsy.DefaultText = "";
            this.txtmBsy.FillColor = System.Drawing.Color.White;
            this.txtmBsy.HideSelection = true;
            this.txtmBsy.IconLeft = null;
            this.txtmBsy.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtmBsy.IconPadding = 10;
            this.txtmBsy.IconRight = null;
            this.txtmBsy.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtmBsy.Lines = new string[0];
            this.txtmBsy.Location = new System.Drawing.Point(111, 35);
            this.txtmBsy.MaxLength = 32767;
            this.txtmBsy.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtmBsy.Modified = false;
            this.txtmBsy.Multiline = false;
            this.txtmBsy.Name = "txtmBsy";
            stateProperties49.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties49.FillColor = System.Drawing.Color.Empty;
            stateProperties49.ForeColor = System.Drawing.Color.Empty;
            stateProperties49.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtmBsy.OnActiveState = stateProperties49;
            stateProperties50.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties50.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties50.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties50.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtmBsy.OnDisabledState = stateProperties50;
            stateProperties51.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties51.FillColor = System.Drawing.Color.Empty;
            stateProperties51.ForeColor = System.Drawing.Color.Empty;
            stateProperties51.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtmBsy.OnHoverState = stateProperties51;
            stateProperties52.BorderColor = System.Drawing.Color.Silver;
            stateProperties52.FillColor = System.Drawing.Color.White;
            stateProperties52.ForeColor = System.Drawing.Color.Empty;
            stateProperties52.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtmBsy.OnIdleState = stateProperties52;
            this.txtmBsy.Padding = new System.Windows.Forms.Padding(3);
            this.txtmBsy.PasswordChar = '\0';
            this.txtmBsy.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtmBsy.PlaceholderText = "Enter text";
            this.txtmBsy.ReadOnly = false;
            this.txtmBsy.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtmBsy.SelectedText = "";
            this.txtmBsy.SelectionLength = 0;
            this.txtmBsy.SelectionStart = 0;
            this.txtmBsy.ShortcutsEnabled = true;
            this.txtmBsy.Size = new System.Drawing.Size(245, 35);
            this.txtmBsy.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtmBsy.TabIndex = 43;
            this.txtmBsy.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtmBsy.TextMarginBottom = 0;
            this.txtmBsy.TextMarginLeft = 3;
            this.txtmBsy.TextMarginTop = 0;
            this.txtmBsy.TextPlaceholder = "Enter text";
            this.txtmBsy.UseSystemPasswordChar = false;
            this.txtmBsy.WordWrap = true;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(8, 128);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(97, 16);
            this.label4.TabIndex = 45;
            this.label4.Text = "Chuyên khoa";
            // 
            // txtChuyenKhoa
            // 
            this.txtChuyenKhoa.AcceptsReturn = false;
            this.txtChuyenKhoa.AcceptsTab = false;
            this.txtChuyenKhoa.AnimationSpeed = 200;
            this.txtChuyenKhoa.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtChuyenKhoa.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtChuyenKhoa.BackColor = System.Drawing.Color.Transparent;
            this.txtChuyenKhoa.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtChuyenKhoa.BackgroundImage")));
            this.txtChuyenKhoa.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtChuyenKhoa.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtChuyenKhoa.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtChuyenKhoa.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtChuyenKhoa.BorderRadius = 10;
            this.txtChuyenKhoa.BorderThickness = 1;
            this.txtChuyenKhoa.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtChuyenKhoa.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtChuyenKhoa.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F);
            this.txtChuyenKhoa.DefaultText = "";
            this.txtChuyenKhoa.FillColor = System.Drawing.Color.White;
            this.txtChuyenKhoa.HideSelection = true;
            this.txtChuyenKhoa.IconLeft = null;
            this.txtChuyenKhoa.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtChuyenKhoa.IconPadding = 10;
            this.txtChuyenKhoa.IconRight = null;
            this.txtChuyenKhoa.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtChuyenKhoa.Lines = new string[0];
            this.txtChuyenKhoa.Location = new System.Drawing.Point(111, 118);
            this.txtChuyenKhoa.MaxLength = 32767;
            this.txtChuyenKhoa.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtChuyenKhoa.Modified = false;
            this.txtChuyenKhoa.Multiline = false;
            this.txtChuyenKhoa.Name = "txtChuyenKhoa";
            stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtChuyenKhoa.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtChuyenKhoa.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtChuyenKhoa.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Silver;
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtChuyenKhoa.OnIdleState = stateProperties48;
            this.txtChuyenKhoa.Padding = new System.Windows.Forms.Padding(3);
            this.txtChuyenKhoa.PasswordChar = '\0';
            this.txtChuyenKhoa.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtChuyenKhoa.PlaceholderText = "Enter text";
            this.txtChuyenKhoa.ReadOnly = false;
            this.txtChuyenKhoa.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtChuyenKhoa.SelectedText = "";
            this.txtChuyenKhoa.SelectionLength = 0;
            this.txtChuyenKhoa.SelectionStart = 0;
            this.txtChuyenKhoa.ShortcutsEnabled = true;
            this.txtChuyenKhoa.Size = new System.Drawing.Size(245, 35);
            this.txtChuyenKhoa.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtChuyenKhoa.TabIndex = 44;
            this.txtChuyenKhoa.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtChuyenKhoa.TextMarginBottom = 0;
            this.txtChuyenKhoa.TextMarginLeft = 3;
            this.txtChuyenKhoa.TextMarginTop = 0;
            this.txtChuyenKhoa.TextPlaceholder = "Enter text";
            this.txtChuyenKhoa.UseSystemPasswordChar = false;
            this.txtChuyenKhoa.WordWrap = true;
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(370, 129);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(75, 16);
            this.label5.TabIndex = 47;
            this.label5.Text = "K/Nghiệm";
            // 
            // txtExp
            // 
            this.txtExp.AcceptsReturn = false;
            this.txtExp.AcceptsTab = false;
            this.txtExp.AnimationSpeed = 200;
            this.txtExp.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtExp.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtExp.BackColor = System.Drawing.Color.Transparent;
            this.txtExp.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtExp.BackgroundImage")));
            this.txtExp.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtExp.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtExp.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtExp.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtExp.BorderRadius = 10;
            this.txtExp.BorderThickness = 1;
            this.txtExp.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtExp.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtExp.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F);
            this.txtExp.DefaultText = "";
            this.txtExp.FillColor = System.Drawing.Color.White;
            this.txtExp.HideSelection = true;
            this.txtExp.IconLeft = null;
            this.txtExp.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtExp.IconPadding = 10;
            this.txtExp.IconRight = null;
            this.txtExp.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtExp.Lines = new string[0];
            this.txtExp.Location = new System.Drawing.Point(451, 118);
            this.txtExp.MaxLength = 32767;
            this.txtExp.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtExp.Modified = false;
            this.txtExp.Multiline = false;
            this.txtExp.Name = "txtExp";
            stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtExp.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtExp.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtExp.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtExp.OnIdleState = stateProperties44;
            this.txtExp.Padding = new System.Windows.Forms.Padding(3);
            this.txtExp.PasswordChar = '\0';
            this.txtExp.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtExp.PlaceholderText = "Enter text";
            this.txtExp.ReadOnly = false;
            this.txtExp.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtExp.SelectedText = "";
            this.txtExp.SelectionLength = 0;
            this.txtExp.SelectionStart = 0;
            this.txtExp.ShortcutsEnabled = true;
            this.txtExp.Size = new System.Drawing.Size(332, 35);
            this.txtExp.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtExp.TabIndex = 46;
            this.txtExp.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtExp.TextMarginBottom = 0;
            this.txtExp.TextMarginLeft = 3;
            this.txtExp.TextMarginTop = 0;
            this.txtExp.TextPlaceholder = "Enter text";
            this.txtExp.UseSystemPasswordChar = false;
            this.txtExp.WordWrap = true;
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.Location = new System.Drawing.Point(373, 170);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(74, 16);
            this.label6.TabIndex = 51;
            this.label6.Text = "Bằng cấp";
            // 
            // txtbcap
            // 
            this.txtbcap.AcceptsReturn = false;
            this.txtbcap.AcceptsTab = false;
            this.txtbcap.AnimationSpeed = 200;
            this.txtbcap.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtbcap.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtbcap.BackColor = System.Drawing.Color.Transparent;
            this.txtbcap.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtbcap.BackgroundImage")));
            this.txtbcap.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtbcap.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtbcap.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtbcap.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtbcap.BorderRadius = 10;
            this.txtbcap.BorderThickness = 1;
            this.txtbcap.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtbcap.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtbcap.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F);
            this.txtbcap.DefaultText = "";
            this.txtbcap.FillColor = System.Drawing.Color.White;
            this.txtbcap.HideSelection = true;
            this.txtbcap.IconLeft = null;
            this.txtbcap.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtbcap.IconPadding = 10;
            this.txtbcap.IconRight = null;
            this.txtbcap.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtbcap.Lines = new string[0];
            this.txtbcap.Location = new System.Drawing.Point(454, 159);
            this.txtbcap.MaxLength = 32767;
            this.txtbcap.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtbcap.Modified = false;
            this.txtbcap.Multiline = false;
            this.txtbcap.Name = "txtbcap";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtbcap.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtbcap.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtbcap.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtbcap.OnIdleState = stateProperties36;
            this.txtbcap.Padding = new System.Windows.Forms.Padding(3);
            this.txtbcap.PasswordChar = '\0';
            this.txtbcap.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtbcap.PlaceholderText = "Enter text";
            this.txtbcap.ReadOnly = false;
            this.txtbcap.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtbcap.SelectedText = "";
            this.txtbcap.SelectionLength = 0;
            this.txtbcap.SelectionStart = 0;
            this.txtbcap.ShortcutsEnabled = true;
            this.txtbcap.Size = new System.Drawing.Size(329, 35);
            this.txtbcap.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtbcap.TabIndex = 50;
            this.txtbcap.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtbcap.TextMarginBottom = 0;
            this.txtbcap.TextMarginLeft = 3;
            this.txtbcap.TextMarginTop = 0;
            this.txtbcap.TextPlaceholder = "Enter text";
            this.txtbcap.UseSystemPasswordChar = false;
            this.txtbcap.WordWrap = true;
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.Location = new System.Drawing.Point(9, 168);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(51, 16);
            this.label7.TabIndex = 49;
            this.label7.Text = "Số ĐT";
            // 
            // txtPhone
            // 
            this.txtPhone.AcceptsReturn = false;
            this.txtPhone.AcceptsTab = false;
            this.txtPhone.AnimationSpeed = 200;
            this.txtPhone.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPhone.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPhone.BackColor = System.Drawing.Color.Transparent;
            this.txtPhone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPhone.BackgroundImage")));
            this.txtPhone.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtPhone.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPhone.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtPhone.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPhone.BorderRadius = 10;
            this.txtPhone.BorderThickness = 1;
            this.txtPhone.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPhone.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhone.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F);
            this.txtPhone.DefaultText = "";
            this.txtPhone.FillColor = System.Drawing.Color.White;
            this.txtPhone.HideSelection = true;
            this.txtPhone.IconLeft = null;
            this.txtPhone.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhone.IconPadding = 10;
            this.txtPhone.IconRight = null;
            this.txtPhone.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhone.Lines = new string[0];
            this.txtPhone.Location = new System.Drawing.Point(114, 159);
            this.txtPhone.MaxLength = 32767;
            this.txtPhone.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPhone.Modified = false;
            this.txtPhone.Multiline = false;
            this.txtPhone.Name = "txtPhone";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhone.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPhone.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhone.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhone.OnIdleState = stateProperties40;
            this.txtPhone.Padding = new System.Windows.Forms.Padding(3);
            this.txtPhone.PasswordChar = '\0';
            this.txtPhone.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPhone.PlaceholderText = "Enter text";
            this.txtPhone.ReadOnly = false;
            this.txtPhone.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPhone.SelectedText = "";
            this.txtPhone.SelectionLength = 0;
            this.txtPhone.SelectionStart = 0;
            this.txtPhone.ShortcutsEnabled = true;
            this.txtPhone.Size = new System.Drawing.Size(245, 35);
            this.txtPhone.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPhone.TabIndex = 48;
            this.txtPhone.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPhone.TextMarginBottom = 0;
            this.txtPhone.TextMarginLeft = 3;
            this.txtPhone.TextMarginTop = 0;
            this.txtPhone.TextPlaceholder = "Enter text";
            this.txtPhone.UseSystemPasswordChar = false;
            this.txtPhone.WordWrap = true;
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.Location = new System.Drawing.Point(12, 86);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(55, 16);
            this.label8.TabIndex = 53;
            this.label8.Text = "Địa chỉ";
            // 
            // txtDcBsy
            // 
            this.txtDcBsy.AcceptsReturn = false;
            this.txtDcBsy.AcceptsTab = false;
            this.txtDcBsy.AnimationSpeed = 200;
            this.txtDcBsy.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDcBsy.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDcBsy.BackColor = System.Drawing.Color.Transparent;
            this.txtDcBsy.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDcBsy.BackgroundImage")));
            this.txtDcBsy.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDcBsy.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDcBsy.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDcBsy.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDcBsy.BorderRadius = 10;
            this.txtDcBsy.BorderThickness = 1;
            this.txtDcBsy.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDcBsy.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDcBsy.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F);
            this.txtDcBsy.DefaultText = "";
            this.txtDcBsy.FillColor = System.Drawing.Color.White;
            this.txtDcBsy.HideSelection = true;
            this.txtDcBsy.IconLeft = null;
            this.txtDcBsy.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDcBsy.IconPadding = 10;
            this.txtDcBsy.IconRight = null;
            this.txtDcBsy.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDcBsy.Lines = new string[0];
            this.txtDcBsy.Location = new System.Drawing.Point(111, 76);
            this.txtDcBsy.MaxLength = 32767;
            this.txtDcBsy.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDcBsy.Modified = false;
            this.txtDcBsy.Multiline = false;
            this.txtDcBsy.Name = "txtDcBsy";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDcBsy.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDcBsy.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDcBsy.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDcBsy.OnIdleState = stateProperties32;
            this.txtDcBsy.Padding = new System.Windows.Forms.Padding(3);
            this.txtDcBsy.PasswordChar = '\0';
            this.txtDcBsy.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDcBsy.PlaceholderText = "Enter text";
            this.txtDcBsy.ReadOnly = false;
            this.txtDcBsy.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDcBsy.SelectedText = "";
            this.txtDcBsy.SelectionLength = 0;
            this.txtDcBsy.SelectionStart = 0;
            this.txtDcBsy.ShortcutsEnabled = true;
            this.txtDcBsy.Size = new System.Drawing.Size(672, 35);
            this.txtDcBsy.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDcBsy.TabIndex = 52;
            this.txtDcBsy.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDcBsy.TextMarginBottom = 0;
            this.txtDcBsy.TextMarginLeft = 3;
            this.txtDcBsy.TextMarginTop = 0;
            this.txtDcBsy.TextPlaceholder = "Enter text";
            this.txtDcBsy.UseSystemPasswordChar = false;
            this.txtDcBsy.WordWrap = true;
            // 
            // FormBsy
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(795, 259);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.txtDcBsy);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.txtbcap);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.txtPhone);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.txtExp);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.txtChuyenKhoa);
            this.Controls.Add(this.txtmBsy);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.txttenBsy);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.button2);
            this.Controls.Add(this.button1);
            this.Controls.Add(this.btnOk);
            this.Controls.Add(this.btnExit);
            this.Controls.Add(this.label3);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FormBsy";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "FormChuyenMuc";
            this.Load += new System.EventHandler(this.FormBsy_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnOk;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnExit;
        private System.Windows.Forms.Button button2;
        private System.Windows.Forms.Button button1;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
        private System.Windows.Forms.Label label8;
        private Bunifu.UI.WinForms.BunifuTextBox txtDcBsy;
        private System.Windows.Forms.Label label6;
        private Bunifu.UI.WinForms.BunifuTextBox txtbcap;
        private System.Windows.Forms.Label label7;
        private Bunifu.UI.WinForms.BunifuTextBox txtPhone;
        private System.Windows.Forms.Label label5;
        private Bunifu.UI.WinForms.BunifuTextBox txtExp;
        private System.Windows.Forms.Label label4;
        private Bunifu.UI.WinForms.BunifuTextBox txtChuyenKhoa;
        private Bunifu.UI.WinForms.BunifuTextBox txtmBsy;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuTextBox txttenBsy;
        private System.Windows.Forms.Label label1;
    }
}